version: "3"

networks:
  proxy:
    external: true
  internal:
    external: false

services:
  blog:
    image: .
    environment:
      NODE_ENV: prod
    labels:
      - traefik.backend=blog
      - traefik.frontend.rule=Host:blog.vaayadi.in
      - traefik.docker.network=proxy
      - traefik.port=80
    networks:
      - internal
      - proxy