version: "3"

networks:
  proxy:
    external: true
  internal:
    external: false

services:
  jaeger:
    image: jaegertracing/all-in-one:1.17
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    labels:
      - traefik.backend=jaeger
      - traefik.frontend.rule=Host:jaeger.southindiantrekkers.org
      - traefik.docker.network=proxy
      - traefik.port=16686
    networks:
      - internal
      - proxy
