version: '3.3'

networks:
  proxy:
    external: true

services:
  golang:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
       - /local/entertainment:/files
    environment:
      - NODE_ENV=prod
    labels:
      - "traefik.port=8100"
      - "traefik.enable=true"
      - "traefik.http.routers.golang.rule=Host(`golang.domain.com`)"
      - "traefik.http.routers.golang.entrypoints=websecure"
      - "traefik.http.routers.golang.tls=true"
      - "traefik.http.routers.golang.tls.certresolver=leresolver"
    networks:
      - proxy
