version: "3"

networks:
  proxy:
    external: true
  internal:
    external: false

services:
  nginx:
    build: 
      context: .
      dockerfile: Dockerfile
    labels:
      - traefik.backend=nginx
      - traefik.frontend.rule=Host:nginx.southindiantrekkers.org
      - traefik.docker.network=proxy
      - traefik.port=80
    networks:
      - internal
      - proxy
