version: "3.3"

networks:
  proxy:
    external: true
services:
  nginx:
    build: 
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.port=80"
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`nginx.domain.com`)"
      - "traefik.http.routers.nginx.entrypoints=websecure"
      - "traefik.http.routers.nginx.tls=true"
      - "traefik.http.routers.nginx.tls.certresolver=leresolver"
    networks:
      - proxy
