version: '3'

networks:
  proxy:
    external: true
  internal:
    external: false

services:
  openvpn:
    cap_add:
     - NET_ADMIN
    image: kylemanna/openvpn
    ports:
     - "1194:1194/udp"
    restart: always
    volumes:
     - ./openvpn-data/conf:/etc/openvpn
    labels:
      - traefik.backend=openvpn
      - traefik.frontend.rule=Host:openvpn.vaayadi.in
      - traefik.docker.network=proxy
      - traefik.port=1194
    networks:
      - internal
      - proxy