version: "3"

networks:
  proxy:
    external: true
  internal:
    external: false

services:
  node:
    build: 
      context: .
      dockerfile: Dockerfile
    labels:
      - traefik.backend=node
      - traefik.frontend.rule=Host:node.vaayadi.in
      - traefik.docker.network=proxy
      - traefik.port=3000
    networks:
      - internal
      - proxy
