version: '3'

networks:
  proxy:
    external: true
  internal:
    external: false

services:
  ui:
    image: portainer/portainer
    restart: always
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock
       - portainer_data:/data
    environment:
      - NODE_ENV=prod
    labels:
      - traefik.backend=ui
      - traefik.frontend.rule=Host:portainer.southindiantrekkers.org
      - traefik.docker.network=proxy
      - traefik.port=9000
    networks:
      - internal
      - proxy


volumes:
  portainer_data:
