version: '3'

networks:
  proxy:
    external: true
  internal:
    external: false

services:
  torrent:
    image: jpillora/cloud-torrent
    volumes:
       - /local/entertainment:/downloads
    environment:
      - NODE_ENV=prod
    labels:
      - traefik.backend=torrent
      - traefik.frontend.rule=Host:torrent.vaayadi.in
      - traefik.docker.network=proxy
      - traefik.port=3000
    networks:
      - internal
      - proxy

